spring:
  application:
    name: "notification-service"
    version: "0.0.1-SNAPSHOT"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_URL}notification
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NOTIFICATION_EMAIL}
    password: ${NOTIFICATION_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group

server:
  port: ${NOTIFICATION_SERVICE_PORT}

jwt:
  secret: ${JWT_SECRET}

kafka:
  topic:
    user-registered: user-registered