spring:
  application:
    name: "transaction-service"
    version: "0.0.1-SNAPSHOT"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_URL}transaction
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

server:
  port: ${TRANSACTION_SERVICE_PORT}

jwt:
  secret: ${JWT_SECRET}

frontend:
  url: ${FRONTEND_URL}

grpc:
  server:
    port: ${TRANSACTION_SERVICE_GRPC_PORT:9091}
  client:
    user-service:
      host: ${USER_SERVICE_HOST:localhost}
      port: ${USER_SERVICE_GRPC_PORT:9090}